/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyecto;

import javax.swing.DefaultComboBoxModel;
import javax.swing.ImageIcon;
import utils.VerData;

/**
 *
 * @author PILAR CARRASCO
 */
public class caracteristicas_vivienda extends javax.swing.JFrame {

    /**
     * Creates new form caracteristicas_vivienda
     */
    public caracteristicas_vivienda() {
        initComponents();
        this.setSize(685, 780);
        setModelo ();
        setModelo2 ();
    }
    
    public void setModelo () 
    {
       //String labels[] = { "Avion", "Burro","Casa","D","E"}; 
        VerData vd = new VerData();
        String labels []= vd.getDistritos();
       final DefaultComboBoxModel model = new DefaultComboBoxModel(labels);
       jComboBox7.setModel(model);
    }
    public void setModelo2 () 
    {
       //String labels[] = { "Avion", "Burro","Casa","D","E"}; 
        VerData vd = new VerData();
        String labels []= vd.getProvincia();
       final DefaultComboBoxModel model = new DefaultComboBoxModel(labels);
       jComboBox9.setModel(model);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        jComboBox3 = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        jComboBox4 = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        jComboBox5 = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jComboBox6 = new javax.swing.JComboBox<>();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jComboBox7 = new javax.swing.JComboBox<>();
        jComboBox8 = new javax.swing.JComboBox<>();
        jComboBox9 = new javax.swing.JComboBox<>();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jRadioButton3 = new javax.swing.JRadioButton();
        jRadioButton4 = new javax.swing.JRadioButton();
        jRadioButton5 = new javax.swing.JRadioButton();
        jRadioButton6 = new javax.swing.JRadioButton();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton7 = new javax.swing.JRadioButton();
        jRadioButton8 = new javax.swing.JRadioButton();
        jRadioButton9 = new javax.swing.JRadioButton();
        jRadioButton10 = new javax.swing.JRadioButton();
        jRadioButton11 = new javax.swing.JRadioButton();
        jRadioButton12 = new javax.swing.JRadioButton();
        jRadioButton13 = new javax.swing.JRadioButton();
        jRadioButton14 = new javax.swing.JRadioButton();
        jRadioButton15 = new javax.swing.JRadioButton();
        jRadioButton16 = new javax.swing.JRadioButton();
        jRadioButton17 = new javax.swing.JRadioButton();
        jRadioButton18 = new javax.swing.JRadioButton();
        jRadioButton19 = new javax.swing.JRadioButton();
        jRadioButton20 = new javax.swing.JRadioButton();
        jRadioButton21 = new javax.swing.JRadioButton();
        jRadioButton22 = new javax.swing.JRadioButton();
        jRadioButton23 = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setSize(new java.awt.Dimension(670, 900));
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(102, 102, 255));
        jPanel1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel1.setMinimumSize(new java.awt.Dimension(580, 590));
        jPanel1.setPreferredSize(new java.awt.Dimension(580, 1000));
        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Sitka Small", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 102, 255));
        jLabel1.setText("Características de la vivienda");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(698, 11, 285, 23);

        jLabel2.setBackground(new java.awt.Color(51, 51, 51));
        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Material de las paredes");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(30, 300, 150, 20);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Características ");
        jLabel4.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jPanel1.add(jLabel4);
        jLabel4.setBounds(230, 260, 240, 40);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Adobe", "Cemento", "Madera", "Quincha", "Otros" }));
        jComboBox1.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBox1ItemStateChanged(evt);
            }
        });
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        jComboBox1.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                jComboBox1PropertyChange(evt);
            }
        });
        jPanel1.add(jComboBox1);
        jComboBox1.setBounds(30, 430, 120, 20);

        jLabel3.setBackground(new java.awt.Color(0, 255, 255));
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/madera.jpg"))); // NOI18N
        jLabel3.setText("jLabel3");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(550, 910, 110, 110);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Material del techo");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(250, 295, 110, 30);

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Calamina", "Caña", "Eternit", "Madera", "Noble", "Paja", " " }));
        jComboBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox2ActionPerformed(evt);
            }
        });
        jPanel1.add(jComboBox2);
        jComboBox2.setBounds(250, 450, 120, 20);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Material del piso");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(470, 295, 102, 30);

        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Cemento", "Losetas", "Madera", "Parquet", "Tierra", "Otros.", " ", " " }));
        jComboBox3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox3ActionPerformed(evt);
            }
        });
        jPanel1.add(jComboBox3);
        jComboBox3.setBounds(470, 450, 120, 20);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Disposición de basura");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(30, 510, 140, 15);

        jComboBox4.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " ", " ", " " }));
        jComboBox4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox4ActionPerformed(evt);
            }
        });
        jPanel1.add(jComboBox4);
        jComboBox4.setBounds(30, 530, 120, 20);

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Riesgo del entorno");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(470, 500, 117, 30);

        jComboBox5.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Alcoholismo", "Basural", "Contaminantes", "Delincuencia", "Huaycos", "Inservibles", "Inundaciones", "Lluvias", "No_asfalto", "Riesgo_entorno", "Sin_luz", "Vectores", " ", " ", " ", " ", " ", " " }));
        jPanel1.add(jComboBox5);
        jComboBox5.setBounds(470, 530, 120, 20);

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        jLabel10.setText("Características");
        jPanel1.add(jLabel10);
        jLabel10.setBounds(230, 260, 230, 40);

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/casac.jpg"))); // NOI18N
        jPanel1.add(jLabel9);
        jLabel9.setBounds(0, -10, 674, 160);

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Eliminación de excretas");
        jPanel1.add(jLabel11);
        jLabel11.setBounds(250, 510, 150, 15);

        jComboBox6.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Acequia", "Aire libre", "Letrina", "Pozo", "Red pública", "Otros" }));
        jComboBox6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox6ActionPerformed(evt);
            }
        });
        jPanel1.add(jComboBox6);
        jComboBox6.setBounds(250, 700, 120, 20);

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Localidad");
        jPanel1.add(jLabel12);
        jLabel12.setBounds(20, 200, 60, 15);

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Provincia");
        jPanel1.add(jLabel13);
        jLabel13.setBounds(240, 200, 60, 15);

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Distrito");
        jPanel1.add(jLabel14);
        jLabel14.setBounds(470, 200, 50, 15);

        jComboBox7.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel1.add(jComboBox7);
        jComboBox7.setBounds(530, 200, 130, 20);

        jComboBox8.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Lima" }));
        jPanel1.add(jComboBox8);
        jComboBox8.setBounds(90, 200, 130, 20);

        jComboBox9.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel1.add(jComboBox9);
        jComboBox9.setBounds(320, 200, 130, 20);

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("Localización");
        jPanel1.add(jLabel16);
        jLabel16.setBounds(240, 150, 190, 37);

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("Dirección");
        jPanel1.add(jLabel17);
        jLabel17.setBounds(110, 240, 60, 15);

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        jPanel1.add(jTextField1);
        jTextField1.setBounds(190, 230, 410, 30);

        jButton1.setBackground(new java.awt.Color(204, 255, 255));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton1.setText("Reporte");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(300, 930, 120, 40);

        jRadioButton2.setText("Adobe");
        jPanel1.add(jRadioButton2);
        jRadioButton2.setBounds(30, 320, 57, 23);

        jRadioButton3.setText("Cemento");
        jPanel1.add(jRadioButton3);
        jRadioButton3.setBounds(30, 340, 69, 23);

        jRadioButton4.setText("Madera");
        jPanel1.add(jRadioButton4);
        jRadioButton4.setBounds(30, 360, 61, 23);

        jRadioButton5.setText("Quincha");
        jPanel1.add(jRadioButton5);
        jRadioButton5.setBounds(30, 380, 65, 23);

        jRadioButton6.setText("Otros");
        jPanel1.add(jRadioButton6);
        jRadioButton6.setBounds(30, 400, 53, 23);

        jRadioButton1.setText("Calamina");
        jPanel1.add(jRadioButton1);
        jRadioButton1.setBounds(250, 320, 90, 23);

        jRadioButton7.setText("Caña");
        jPanel1.add(jRadioButton7);
        jRadioButton7.setBounds(250, 340, 70, 23);

        jRadioButton8.setText("Eternit");
        jPanel1.add(jRadioButton8);
        jRadioButton8.setBounds(250, 360, 70, 23);

        jRadioButton9.setText("Madera");
        jPanel1.add(jRadioButton9);
        jRadioButton9.setBounds(250, 380, 70, 23);

        jRadioButton10.setText("Noble");
        jPanel1.add(jRadioButton10);
        jRadioButton10.setBounds(250, 400, 70, 23);

        jRadioButton11.setText("Paja");
        jPanel1.add(jRadioButton11);
        jRadioButton11.setBounds(250, 420, 47, 23);

        jRadioButton12.setText("Cemento");
        jPanel1.add(jRadioButton12);
        jRadioButton12.setBounds(470, 320, 100, 23);

        jRadioButton13.setText("Losetas");
        jPanel1.add(jRadioButton13);
        jRadioButton13.setBounds(470, 340, 100, 23);

        jRadioButton14.setText("Madera");
        jPanel1.add(jRadioButton14);
        jRadioButton14.setBounds(470, 360, 100, 23);

        jRadioButton15.setText("Parquet");
        jPanel1.add(jRadioButton15);
        jRadioButton15.setBounds(470, 380, 100, 23);

        jRadioButton16.setText("Tierra");
        jPanel1.add(jRadioButton16);
        jRadioButton16.setBounds(470, 400, 90, 23);

        jRadioButton17.setText("Otros");
        jPanel1.add(jRadioButton17);
        jRadioButton17.setBounds(470, 420, 53, 23);

        jRadioButton18.setText("Aire Libre");
        jPanel1.add(jRadioButton18);
        jRadioButton18.setBounds(250, 540, 90, 23);

        jRadioButton19.setText("Acequia");
        jPanel1.add(jRadioButton19);
        jRadioButton19.setBounds(250, 560, 90, 23);

        jRadioButton20.setText("Red pública");
        jPanel1.add(jRadioButton20);
        jRadioButton20.setBounds(250, 580, 90, 23);

        jRadioButton21.setText("Letrina");
        jPanel1.add(jRadioButton21);
        jRadioButton21.setBounds(250, 600, 90, 23);

        jRadioButton22.setText("Pozo");
        jPanel1.add(jRadioButton22);
        jRadioButton22.setBounds(250, 620, 90, 23);

        jRadioButton23.setText("Otros");
        jPanel1.add(jRadioButton23);
        jRadioButton23.setBounds(250, 640, 80, 23);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 670, 650);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox2ActionPerformed

    private void jComboBox1PropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_jComboBox1PropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1PropertyChange

    
    private void jComboBox1ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBox1ItemStateChanged
        // TODO add your handling code here:
        //String material = jComboBox1
        //System.out.println(material);
        //jLabel3.setIcon(new ImageIcon("C:/Users/PILAR CARRASCO/Desktop/nuevo/SistemaMinsa/src/iconos/cemento.jpg"));
    }//GEN-LAST:event_jComboBox1ItemStateChanged

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jComboBox6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox6ActionPerformed

    private void jComboBox4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox4ActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
         Reporte abd = new Reporte();
        abd.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jComboBox3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox3ActionPerformed

    /**
     * @param args the command line arguments
     */
      public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(caracteristicas_vivienda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(caracteristicas_vivienda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(caracteristicas_vivienda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(caracteristicas_vivienda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new caracteristicas_vivienda().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JComboBox<String> jComboBox3;
    private javax.swing.JComboBox<String> jComboBox4;
    private javax.swing.JComboBox<String> jComboBox5;
    private javax.swing.JComboBox<String> jComboBox6;
    private javax.swing.JComboBox<String> jComboBox7;
    private javax.swing.JComboBox<String> jComboBox8;
    private javax.swing.JComboBox<String> jComboBox9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton10;
    private javax.swing.JRadioButton jRadioButton11;
    private javax.swing.JRadioButton jRadioButton12;
    private javax.swing.JRadioButton jRadioButton13;
    private javax.swing.JRadioButton jRadioButton14;
    private javax.swing.JRadioButton jRadioButton15;
    private javax.swing.JRadioButton jRadioButton16;
    private javax.swing.JRadioButton jRadioButton17;
    private javax.swing.JRadioButton jRadioButton18;
    private javax.swing.JRadioButton jRadioButton19;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton20;
    private javax.swing.JRadioButton jRadioButton21;
    private javax.swing.JRadioButton jRadioButton22;
    private javax.swing.JRadioButton jRadioButton23;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JRadioButton jRadioButton4;
    private javax.swing.JRadioButton jRadioButton5;
    private javax.swing.JRadioButton jRadioButton6;
    private javax.swing.JRadioButton jRadioButton7;
    private javax.swing.JRadioButton jRadioButton8;
    private javax.swing.JRadioButton jRadioButton9;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
