/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyecto;

/**
 *
 * @author LENOVO
 */
public class PanelMenu extends javax.swing.JFrame {

    /**
     * Creates new form panelMenu
     */
    public PanelMenu() {
        initComponents();
        this.setLocationRelativeTo(null); 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToolBar1 = new javax.swing.JToolBar();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        btn_newFamilia = new javax.swing.JButton();
        btn_famregistrada = new javax.swing.JButton();
        btn_reportes = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        jToolBar1.setRollover(true);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(204, 255, 255));
        setSize(new java.awt.Dimension(1000, 800));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Charlemagne Std", 3, 14)); // NOI18N
        jLabel3.setText("Familia registrada");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 380, -1, -1));

        jLabel2.setFont(new java.awt.Font("Charlemagne Std", 3, 14)); // NOI18N
        jLabel2.setText("Nueva Familia");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 120, -1, -1));

        jLabel4.setFont(new java.awt.Font("Charlemagne Std", 3, 14)); // NOI18N
        jLabel4.setText("Reportes");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 380, -1, -1));

        btn_newFamilia.setBackground(new java.awt.Color(0, 0, 0));
        btn_newFamilia.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/gohan1.png"))); // NOI18N
        btn_newFamilia.setAlignmentY(0.0F);
        btn_newFamilia.setBorder(null);
        btn_newFamilia.setContentAreaFilled(false);
        btn_newFamilia.setDisabledIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/gohan3.png"))); // NOI18N
        btn_newFamilia.setDisabledSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/gohan3.png"))); // NOI18N
        btn_newFamilia.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/gohan2.png"))); // NOI18N
        btn_newFamilia.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/gohan2.png"))); // NOI18N
        btn_newFamilia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_newFamiliaActionPerformed(evt);
            }
        });
        getContentPane().add(btn_newFamilia, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 20, 90, 90));

        btn_famregistrada.setBackground(new java.awt.Color(0, 0, 0));
        btn_famregistrada.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/gok1.png"))); // NOI18N
        btn_famregistrada.setAlignmentY(0.0F);
        btn_famregistrada.setBorder(null);
        btn_famregistrada.setContentAreaFilled(false);
        btn_famregistrada.setDisabledIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/gok3.png"))); // NOI18N
        btn_famregistrada.setDisabledSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/gok3.png"))); // NOI18N
        btn_famregistrada.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/gok2.png"))); // NOI18N
        btn_famregistrada.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/gok2.png"))); // NOI18N
        btn_famregistrada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_famregistradaActionPerformed(evt);
            }
        });
        getContentPane().add(btn_famregistrada, new org.netbeans.lib.awtextra.AbsoluteConstraints(43, 273, 120, 90));

        btn_reportes.setBackground(new java.awt.Color(0, 0, 0));
        btn_reportes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/veg1.png"))); // NOI18N
        btn_reportes.setAlignmentY(0.0F);
        btn_reportes.setBorder(null);
        btn_reportes.setContentAreaFilled(false);
        btn_reportes.setDisabledIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/veg3.png"))); // NOI18N
        btn_reportes.setDisabledSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/veg3.png"))); // NOI18N
        btn_reportes.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/veg2.png"))); // NOI18N
        btn_reportes.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/veg2.png"))); // NOI18N
        btn_reportes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_reportesActionPerformed(evt);
            }
        });
        getContentPane().add(btn_reportes, new org.netbeans.lib.awtextra.AbsoluteConstraints(433, 273, 110, 90));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/minsa3.JPG"))); // NOI18N
        jLabel1.setText("marco");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 580, 410));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_newFamiliaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_newFamiliaActionPerformed
        // TODO add your handling code here:
        FichaFamiliar rf = new FichaFamiliar();
        rf.setVisible(true);
        dispose();
 
    }//GEN-LAST:event_btn_newFamiliaActionPerformed

    private void btn_reportesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_reportesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_reportesActionPerformed

    private void btn_famregistradaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_famregistradaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_famregistradaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PanelMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PanelMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PanelMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PanelMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PanelMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_famregistrada;
    private javax.swing.JButton btn_newFamilia;
    private javax.swing.JButton btn_reportes;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JToolBar jToolBar1;
    // End of variables declaration//GEN-END:variables
}
